url: "https://mochimilk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "pureui" # the subpath of your site, e.g. /blog
title: "PureUI" # the name of your site, e.g. ACME Corp.